In [1]:
#Use the following code for the questions below:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [2]:
#1. How many negative numbers are there?
negative_numbers = a < 0
len(a[negative_numbers])

4

In [3]:
#2. How many positive numbers are there?
positive_numbers = a > 0
len(a[positive_numbers])

5

In [4]:
#3. How many even positive numbers are there?
positive_even_numbers = (a > 0) & (a % 2 == 0)
len(a[positive_even_numbers])

3

In [5]:
#4. If you were to add 3 to each data point, how many positive numbers would there be?
positive_numbers = (a + 3) > 0
len(a[positive_numbers])

10

In [6]:
#5. If you squared each number, what would the new mean and standard deviation be?
a.mean() ** 2

9.0

In [7]:
a.std() ** 2

64.99999999999999

In [8]:
#6. A common statistical operation on a dataset is centering. This means to adjust the data such that the center of the data is at 0. This is done by subtracting the mean from each data point. Center the data set.
a - a.mean()

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [9]:
#7. Calculate the z-score for each data point. Recall that the z-score is given by:
# Z = x − μ / σ
(a - a.mean()) / a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [10]:
#8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [11]:
import numpy as np
# Life w/o numpy to life with numpy

# Setup 1

In [12]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [13]:
# Use python's built in functionality/operators to determine the following:

In [14]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
def sum_of_a(nums):
    sum_list = 0
    for num in nums:
        sum_list = sum_list + num
    return sum_list
print(sum_of_a(a))

55


In [15]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.sum()

55

In [16]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
def min_of_a(nums):
    num_list = []
    for num in nums:
        num_list.append(num)
    return min(num_list)
print(min_of_a(a))

1


In [17]:
a.min()

1

In [18]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
def max_of_a(nums):
    num_list = []
    for num in nums:
        num_list.append(num)
    return max(num_list)
print(max_of_a(a))

10


In [19]:
a.max()

10

In [20]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
def mean_of_a(nums):
    sum_num = 0
    for num in nums:
        sum_num = sum_num + num           
        avg = sum_num / len(nums)
    return avg
print(mean_of_a(a))

5.5


In [21]:
a.mean()

5.5

In [22]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
def product_of_a(nums):
    total = 1
    for num in nums:
        total *= num
    return (total)
print(product_of_a(a))

3628800


In [23]:
a.prod() 

3628800

In [24]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
def squares_of_a(nums):
    square_list = []
    for num in nums:
        square_list.append(num**2)
    return (square_list)
print(squares_of_a(a))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [25]:
a**2 

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [26]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
def odds_in_a(nums):
    num_list = []
    for num in nums:
        if num % 2 != 0:
            num_list.append(num)
    return (num_list)
print(odds_in_a(a))

[1, 3, 5, 7, 9]


In [27]:
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

In [28]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
def evens_in_a(nums):
    num_list = []
    for num in nums:
        if num % 2 == 0:
            num_list.append(num)
    return (num_list)
print(evens_in_a(a))

[2, 4, 6, 8, 10]


In [29]:
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10])

# Setup 2

In [30]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

In [31]:
# Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [32]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

In [33]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
print(sum_of_b)

33


In [34]:
b.sum()

33

In [35]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 
print(min_of_b)

3


In [36]:
b.min()

3

In [37]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
print(max_of_b)

8


In [38]:
b.max()

8

In [39]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
print(mean_of_b)

5.5


In [40]:
b.mean()

5.5

In [41]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
print(product_of_b)

20160


In [42]:
b.prod()

20160

In [43]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
print(squares_of_b)

[9, 16, 25, 36, 49, 64]


In [44]:
b**2

array([[ 9, 16, 25],
       [36, 49, 64]])

In [45]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
print(odds_in_b)

[3, 5, 7]


In [46]:
b[b % 2 == 1]

array([3, 5, 7])

In [47]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
print(evens_in_b)

[4, 6, 8]


In [48]:
b[b % 2 == 0]

array([4, 6, 8])

In [49]:
# Exercise 9 - print out the shape of the array b.
b.shape

(2, 3)

In [50]:
# Exercise 10 - transpose the array b.
b.transpose() 

array([[3, 6],
       [4, 7],
       [5, 8]])

In [51]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [52]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
b.reshape((6,1)) 

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# Setup 3

In [53]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [54]:
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

In [55]:
# Exercise 1 - Find the min, max, sum, and product of c.

In [56]:
c.min()

1

In [57]:
c.max()

9

In [58]:
c.sum()

45

In [59]:
c.prod()

362880

In [60]:
# Exercise 2 - Determine the standard deviation of c.

In [61]:
c.std()

2.581988897471611

In [62]:
# Exercise 3 - Determine the variance of c.

In [63]:
sum(sum((c - c.mean())**2 / 9))

6.666666666666666

In [64]:
np.var(c)

6.666666666666667

In [65]:
# Exercise 4 - Print out the shape of the array c.

In [66]:
c.shape

(3, 3)

In [67]:
# Exercise 5 - Transpose c and print out transposed result.

In [68]:
c.transpose() 

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [69]:
# Exercise 6 - Get the dot product of the array c with c. 

In [70]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [71]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [72]:
sum(sum(c * c.transpose()))

261

In [73]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [74]:
c.prod() * c.transpose().prod()

131681894400

# Setup 4

In [75]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

In [76]:
# Exercise 1 - Find the sine of all the numbers in d

In [77]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [78]:
# Exercise 2 - Find the cosine of all the numbers in d

In [79]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [80]:
# Exercise 3 - Find the tangent of all the numbers in d

In [81]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [82]:
# Exercise 4 - Find all the negative numbers in d

In [83]:
negative_numbers = d < 0
(d[negative_numbers])

array([-90, -30, -45, -45])

In [84]:
# Exercise 5 - Find all the positive numbers in d

In [85]:
positive_numbers = d > 0
(d[positive_numbers])

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [86]:
# Exercise 6 - Return an array of only the unique numbers in d.

In [87]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [88]:
# Exercise 7 - Determine how many unique numbers there are in d.

In [89]:
len(np.unique(d))

11

In [90]:
# Exercise 8 - Print out the shape of d.

In [91]:
d.shape

(3, 6)

In [92]:
# Exercise 9 - Transpose and then print out the shape of d.

In [93]:
d.transpose().shape

(6, 3)

In [94]:
# Exercise 10 - Reshape d into an array of 9 x 2

In [95]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

In [96]:
#9. For even more practice, clone https://github.com/rougier/numpy-100, make your own repo called numpy-100, and then commit and push your solutions to your own repo.